In [116]:
%matplotlib inline

torch.tensor
==========================

Тензоры - это специализированная структура данных похожая на массивы и матрицы. В пакете PyTorch тензоры применяются для хранения и обработки входов и выходов нейросетевых моделей, а так же их весов.

Тензорвы очень похожи на ndarray пакета numpy, за исключением того, что они подходят для рассчетов с использованием GPU(NVIDIA/AMD) и поддерживают механизм автоматического дифференцирования Autograd.

In [117]:
import torch
import math
import numpy as np

## Создание тензоров

Создадим неинициализированны тензор. Обратите внимание, что по умолчанию все тензоры имеют тип `torch.FloatTensor`:

In [118]:
x = torch.empty(3,4)
print(f"Tensor type : {type(x)}")
print(f"Tensor data type : {x.type()}")
print(x)

Tensor type : <class 'torch.Tensor'>
Tensor data type : torch.FloatTensor
tensor([[ 0.0000e+00,  4.4766e+00,  9.3233e-02,  1.8976e-01],
        [ 4.0042e-29, -1.5846e+29,  4.0045e-29,  8.5899e+09],
        [ 4.2039e-45, -3.6893e+19,  4.0039e-29, -8.5899e+09]])


Создадим тензоры с константными и случайными значениями:

In [119]:
zeros = torch.zeros(2, 3)
print(f"zeros : {zeros}")

ones = torch.ones(2, 3)
print(f"ones : {ones}")

torch.manual_seed(1729)
random = torch.rand(2, 3)
print(f"random : {random}")

zeros : tensor([[0., 0., 0.],
        [0., 0., 0.]])
ones : tensor([[1., 1., 1.],
        [1., 1., 1.]])
random : tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


__Внимание__, если вам нужна воспроизводимость результатов случайной инициализации, то не забывайте использовать `torch.manual_seed()`
Более подробно о воспроизводимости <a href="https://pytorch.org/docs/stable/notes/randomness.html"> тут <a>

In [120]:
torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(f"random1 : {random1}")

random2 = torch.rand(2, 3)
print(f"random2 : {random2}")

torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(f"random3 : {random3}")

random4 = torch.rand(2, 3)
print(f"random4 : {random4}")

random1 : tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
random2 : tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])
random3 : tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
random4 : tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


Так же в PyTorch есть возможность наследовать размерности других тензоров при создании.

In [121]:
x = torch.empty(2, 2, 3)
print(x.shape)
print(x)

empty_like_x = torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

zeros_like_x = torch.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

ones_like_x = torch.ones_like(x)
print(ones_like_x.shape)
print(ones_like_x)

rand_like_x = torch.rand_like(x)
print(rand_like_x.shape)
print(rand_like_x)

torch.Size([2, 2, 3])
tensor([[[0.6128, 0.1519, 0.0453],
         [0.5035, 0.9978, 0.3884]],

        [[0.6929, 0.1703, 0.1384],
         [0.4759, 0.7481, 0.0361]]])
torch.Size([2, 2, 3])
tensor([[[0.6128, 0.1519, 0.0453],
         [0.5035, 0.9978, 0.3884]],

        [[0.6929, 0.1703, 0.1384],
         [0.4759, 0.7481, 0.0361]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 2, 3])
tensor([[[0.6128, 0.1519, 0.0453],
         [0.5035, 0.9978, 0.3884]],

        [[0.6929, 0.1703, 0.1384],
         [0.4759, 0.7481, 0.0361]]])


Давайте создадим несколько тензоров из типов данных самого python:

In [122]:
some_constants = torch.tensor([[3.1415926, 2.71828], [1.61803, 0.0072897]])
print(some_constants)

some_integers = torch.tensor((2, 3, 5, 7, 11, 13, 17, 19))
print(some_integers)

more_integers = torch.tensor(((2, 4, 6), [3, 6, 9]))
print(more_integers)

tensor([[3.1416, 2.7183],
        [1.6180, 0.0073]])
tensor([ 2,  3,  5,  7, 11, 13, 17, 19])
tensor([[2, 4, 6],
        [3, 6, 9]])


## Типы данных тензоров

В PyTorch тензоры могут хранить различные типы данных в рамках одного объекта, т.е. один `torch.tensor` может содержать внутри себя только один тип данных. Существующие типы данных в PyTorch:
<ul>
<li>torch.bool</li>
<li>torch.int8</li>
<li>torch.uint8</li>
<li>torch.int16</li>
<li>torch.uint16</li>
<li>torch.int32</li>
<li>torch.uint32</li>
<li>torch.half - fp16 </li>
<li>torch.float</li>
<li>torch.double</li>
<li>torch.bfloat - <a href="https://en.wikichip.org/wiki/brain_floating-point_format"> brain float <a> </li> 
</ul>

In [123]:
a = torch.ones((2, 3), dtype=torch.int16)
print(a)

b = torch.rand((2, 3), dtype=torch.float64) * 20.
print(b)

c = b.to(torch.int32)
print(c)

d = c.to(torch.half)
print(d)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[ 0.9956,  1.4148,  5.8364],
        [11.2406, 11.2083, 11.6692]], dtype=torch.float64)
tensor([[ 0,  1,  5],
        [11, 11, 11]], dtype=torch.int32)
tensor([[ 0.,  1.,  5.],
        [11., 11., 11.]], dtype=torch.float16)


## Математические и логические операции

### Операции со скалярами

In [124]:
ones = torch.zeros(2, 2) + 1
twos = torch.ones(2, 2) * 2
threes = (torch.ones(2, 2) * 7 - 1) / 2
fours = twos ** 2
sqrt2s = twos ** 0.5

print(ones)
print(twos)
print(threes)
print(fours)
print(sqrt2s)

tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])


### Такие же операции между парами тензоров

In [125]:
powers2 = twos ** torch.tensor([[1, 2], [3, 4]])
print(powers2)

fives = ones + fours
print(fives)

dozens = threes * fours
print(dozens)

tensor([[ 2.,  4.],
        [ 8., 16.]])
tensor([[5., 5.],
        [5., 5.]])
tensor([[12., 12.],
        [12., 12.]])


А вот что будет, если размерности тензоров не совпадут

In [126]:
a = torch.rand(2, 3)
b = torch.rand(3, 2)

try:
    print(a * b)
except Exception as e:
    print(f"Error occured : {e}")

Error occured : The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1


### Broadcasting операции над `torch.tensor`

In [127]:
rand = torch.rand(2, 4)
aranged = rand * (torch.arange(4) + 1)

print(rand)
print(aranged)

tensor([[0.2024, 0.5731, 0.7191, 0.4067],
        [0.7301, 0.6276, 0.7357, 0.0381]])
tensor([[0.2024, 1.1461, 2.1573, 1.6268],
        [0.7301, 1.2551, 2.2072, 0.1524]])


В примере выше мы построчно перемножили тензор из случайных значений с тензором `torch.tensor([1, 2, 3 ,4])`. Это крайне полезная и нужная операция в Deep Learning. Вот правила, по которым она работает:

 - Каждый из тензоров должен иметь хотя бы одну ненулевую размерность. Нулевые тензоры не бродкастятся!
 - Сравниваем размерности 2-х тензоров от последней к начальной:
 - * Каждая из размерностей должна быть равна ИЛИ
 - * Одна из размерностей должна быть равна 1, ИЛИ
 - * Размерность отсутствует в одном из тензоров.
 
 Рассмотрим примеры:

In [128]:
a =     torch.ones(4, 3, 2)

b = a * torch.rand(   3, 2) # 3rd & 2nd dims identical to a, dim 1 absent
print(b)

c = a * torch.rand(   3, 1) # 3rd dim = 1, 2nd dim identical to a 
print(c)

d = a * torch.rand(   1, 2) # 3rd dim identical to a, 2nd dim = 1
print(d)

tensor([[[0.2138, 0.5395],
         [0.3686, 0.4007],
         [0.7220, 0.8217]],

        [[0.2138, 0.5395],
         [0.3686, 0.4007],
         [0.7220, 0.8217]],

        [[0.2138, 0.5395],
         [0.3686, 0.4007],
         [0.7220, 0.8217]],

        [[0.2138, 0.5395],
         [0.3686, 0.4007],
         [0.7220, 0.8217]]])
tensor([[[0.2612, 0.2612],
         [0.7375, 0.7375],
         [0.8328, 0.8328]],

        [[0.2612, 0.2612],
         [0.7375, 0.7375],
         [0.8328, 0.8328]],

        [[0.2612, 0.2612],
         [0.7375, 0.7375],
         [0.8328, 0.8328]],

        [[0.2612, 0.2612],
         [0.7375, 0.7375],
         [0.8328, 0.8328]]])
tensor([[[0.8444, 0.2941],
         [0.8444, 0.2941],
         [0.8444, 0.2941]],

        [[0.8444, 0.2941],
         [0.8444, 0.2941],
         [0.8444, 0.2941]],

        [[0.8444, 0.2941],
         [0.8444, 0.2941],
         [0.8444, 0.2941]],

        [[0.8444, 0.2941],
         [0.8444, 0.2941],
         [0.8444, 0.2941]]])


Ниже представлены другие математические и логические операции с тензорами:

In [129]:
# common functions
a = torch.rand(2, 4) * 2 - 1
print('Common functions:')
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5, 0.5))

# trigonometric functions and their inverses
angles = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
sines = torch.sin(angles)
inverses = torch.asin(sines)
print('\nSine and arcsine:')
print(angles)
print(sines)
print(inverses)

# bitwise operations
print('\nBitwise XOR:')
b = torch.tensor([1, 5, 11])
c = torch.tensor([2, 7, 10])
print(torch.bitwise_xor(b, c))

# comparisons:
print('\nBroadcasted, element-wise equality comparison:')
d = torch.tensor([[1., 2.], [3., 4.]])
e = torch.ones(1, 2)  # many comparison ops support broadcasting!
print(torch.eq(d, e)) # returns a tensor of type bool

# reductions:
print('\nReduction ops:')
print(torch.max(d))        # returns a single-element tensor
print(torch.max(d).item()) # extracts the value from the returned tensor
print(torch.mean(d))       # average
print(torch.std(d))        # standard deviation
print(torch.prod(d))       # product of all numbers
print(torch.unique(torch.tensor([1, 2, 1, 2, 1, 2]))) # filter unique elements

# vector and linear algebra operations
v1 = torch.tensor([1., 0., 0.])         # x unit vector
v2 = torch.tensor([0., 1., 0.])         # y unit vector
m1 = torch.rand(2, 2)                   # random matrix
m2 = torch.tensor([[3., 0.], [0., 3.]]) # three times identity matrix

print('\nVectors & Matrices:')
print(torch.cross(v2, v1)) # negative of z unit vector (v1 x v2 == -v2 x v1)
print(m1)
m3 = torch.matmul(m1, m2)
print(m3)                  # 3 times m1
print(torch.svd(m3))       # singular value decomposition

Common functions:
tensor([[0.2424, 0.0866, 0.8702, 0.3355],
        [0.5652, 0.7337, 0.9955, 0.0110]])
tensor([[-0., -0., -0., 1.],
        [1., -0., -0., -0.]])
tensor([[-1., -1., -1.,  0.],
        [ 0., -1., -1., -1.]])
tensor([[-0.2424, -0.0866, -0.5000,  0.3355],
        [ 0.5000, -0.5000, -0.5000, -0.0110]])

Sine and arcsine:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 0.7854])

Bitwise XOR:
tensor([3, 2, 1])

Broadcasted, element-wise equality comparison:
tensor([[ True, False],
        [False, False]])

Reduction ops:
tensor(4.)
4.0
tensor(2.5000)
tensor(1.2910)
tensor(24.)
tensor([1, 2])

Vectors & Matrices:
tensor([ 0.,  0., -1.])
tensor([[0.3857, 0.9883],
        [0.4762, 0.7242]])
tensor([[1.1572, 2.9650],
        [1.4287, 2.1726]])
torch.return_types.svd(
U=tensor([[-0.7758, -0.6310],
        [-0.6310,  0.7758]]),
S=tensor([4.0883, 0.4211]),
V=tensor([[-0.4401,  0.8980],
        [-0.8980, -0.4401]]))


## Изменение тензоров без выделения памяти (inplace)

Как правило, любые операции над тензорами так или иначе приводят к выделению памяти. Часто бывает необходимо изменить тензор непосредственно, без создания нового объекта(читай выделения памяти).

In [130]:
a = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print('a:')
print(a)
print(torch.sin(a))   # this operation creates a new tensor in memory
print(a)              # a has not changed

b = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print('\nb:')
print(b)
print(torch.sin_(b))  # note the underscore
print(b)     

a:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 2.3562])

b:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7071, 1.0000, 0.7071])


То же самое с обычными арифметическими операциями

In [131]:
a = torch.ones(2, 2)
b = torch.rand(2, 2)

print('Before:')
print(a)
print(b)
print('\nAfter adding:')
print(a.add_(b))
print(a)
print(b)
print('\nAfter multiplying')
print(b.mul_(b))
print(b)

Before:
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.0776, 0.4004],
        [0.9877, 0.0352]])

After adding:
tensor([[1.0776, 1.4004],
        [1.9877, 1.0352]])
tensor([[1.0776, 1.4004],
        [1.9877, 1.0352]])
tensor([[0.0776, 0.4004],
        [0.9877, 0.0352]])

After multiplying
tensor([[0.0060, 0.1603],
        [0.9756, 0.0012]])
tensor([[0.0060, 0.1603],
        [0.9756, 0.0012]])


Из примеров выше видно, что inplace операции не принадлежат модулю `torch` и предоставляются непосредственно самими изменяемыми тензорами. При необходимости такого же поведения можно достичь встроенными методами модуля, при помощи атрибута `out`.

In [132]:
a = torch.rand(2, 2)
b = torch.rand(2, 2)
c = torch.zeros(2, 2)
old_id = id(c)

print(c)
d = torch.matmul(a, b, out=c)
print(c)                # contents of c have changed

assert c is d           # test c & d are same object, not just containing equal values
assert id(c), old_id    # make sure that our new c is the same object as the old one

torch.rand(2, 2, out=c) # works for creation too!
print(c)                # c has changed again
assert id(c), old_id    # still the same object!

tensor([[0., 0.],
        [0., 0.]])
tensor([[0.4101, 0.1728],
        [0.8007, 0.7183]])
tensor([[0.8441, 0.9004],
        [0.3995, 0.6324]])


## Копирование тензоров

Как и в обычном Python, присваивая переменной значение какого-либо тензора, мы присваиваем ссылку, само значение не копируется.

In [133]:
a = torch.ones(2, 2)
b = a

a[0][1] = 561  # we change a...
print(b)       # ...and b is also altered

tensor([[  1., 561.],
        [  1.,   1.]])


Что делать, если мы хотим скопировать тензор? Все просто - клонируем его!

In [134]:
a = torch.ones(2, 2)
b = a.clone()

assert b is not a      # different objects in memory...
print(torch.eq(a, b))  # ...but still with the same contents!

a[0][1] = 561          # a changes...
print(b)               # ...but b is still all ones

tensor([[True, True],
        [True, True]])
tensor([[1., 1.],
        [1., 1.]])


__ВНИМАНИЕ__ при клонировании тензора, как показано выше, вместе со всем содержимым и клонируется и граф вычислений данного тензора. Что приведет к пробросу градиентов от клона к исходному вектору. Если вы не ожидаете данного поведения, то необходимо дополнительно использовать метод `detach()`. 

In [135]:
a = torch.rand(2, 2, requires_grad=True) # turn on autograd
print(a)

b = a.clone()
print(b)

c = a.detach().clone()
print(c)

print(a)

tensor([[0.9464, 0.0113],
        [0.5183, 0.9807]], requires_grad=True)
tensor([[0.9464, 0.0113],
        [0.5183, 0.9807]], grad_fn=<CloneBackward0>)
tensor([[0.9464, 0.0113],
        [0.5183, 0.9807]])
tensor([[0.9464, 0.0113],
        [0.5183, 0.9807]], requires_grad=True)


## Работа с GPU

Для работы PyTorch с GPU первоначально необходимо удостовериться, что GPU доступен.

In [136]:
if torch.cuda.is_available():
    print('We have a GPU!')
else:
    print('Sorry, CPU only.')

Sorry, CPU only.


При создании тензора возможно указать устройство, в памяти которого, он должен быть размещен. По-умолчанию, все тензоры размещаются на CPU.

In [137]:
if torch.cuda.is_available():
    gpu_rand = torch.rand(2, 2, device='cuda')
    print(f"gpu_rand : {gpu_rand}, {gpu_rand.device}")
else:
    cpu_rand = torch.rand(2, 2, device='cpu')
    print(f"cpu_rand : {cpu_rand}, {cpu_rand.device}")

cpu_rand : tensor([[0.6545, 0.4144],
        [0.0696, 0.4648]]), cpu


Количество доступных PyTorch GPU можно узнать при помощи: `torch.cuda.device_count()`. Если в системе более, чем одна GPU, то они могут быть обозначены строками: `device='cuda:0'`, `device='cuda:1'`.
Для переноса уже существующего тензора на то или иное устройство, необходимо использовать метод `.to()`.

In [138]:
if torch.cuda.is_available():
    my_device = torch.device('cuda')
else:
    my_device = torch.device('cpu')
print('Device: {}'.format(my_device))

y = torch.rand(2, 2)
y = y.to(my_device)

Device: cpu


Если в вычислениях участвуют несколько тензоров, то нужно быть уверенным, что все они находятся на одном и том же устройстве.

In [139]:
x = torch.rand(2, 2)
y = torch.rand(2, 2, device='gpu')
try:
    z = x + y  # exception will be thrown
except Exception as e:
    print(f"Error occured : {e}")

RuntimeError: Expected one of cpu, cuda, xpu, mkldnn, opengl, opencl, ideep, hip, ve, ort, mlc, xla, lazy, vulkan, meta, hpu device type at start of device string: gpu

## Работа с размерностями `torch.tensor`

Как правило, модели в PyTorch на вход принимают тензоры определенной размерности. Например, большинство предобученных сверточных нейросетей использюут в качестве входа тензоры размерности (N, 3, 226, 226), где N - кол-во картинок в батче. Чтобы подать на вход такой сети одну картинку, ее нужно привести в данному формату входа.

In [140]:
a = torch.rand(3, 226, 226)
b = a.unsqueeze(0)

print(a.shape)
print(b.shape)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


Рассмотрим еще несколько примеров схлопывания и расхлопывания размерностей

In [141]:
a = torch.rand(1, 20)
print(a.shape)
print(a)

b = a.squeeze(0)
print(b.shape)
print(b)

c = torch.rand(2, 2)
print(c.shape)

d = c.squeeze(0)
print(d.shape)

torch.Size([1, 20])
tensor([[0.3277, 0.5210, 0.7349, 0.7823, 0.8637, 0.1891, 0.3952, 0.9176, 0.8960,
         0.4887, 0.8625, 0.6191, 0.9935, 0.1844, 0.6138, 0.6854, 0.0438, 0.0636,
         0.2884, 0.4362]])
torch.Size([20])
tensor([0.3277, 0.5210, 0.7349, 0.7823, 0.8637, 0.1891, 0.3952, 0.9176, 0.8960,
        0.4887, 0.8625, 0.6191, 0.9935, 0.1844, 0.6138, 0.6854, 0.0438, 0.0636,
        0.2884, 0.4362])
torch.Size([2, 2])
torch.Size([2, 2])


Разрешено производить `squeeze`(cхлопывание) размерностей = 1, симметрично `unsqueeze`(расхлопываение) создает доп-ную размерность равную 1.
Рассмотрим пример, когда `unsqueeze` позволяет применить операцию broadcasting'a:

In [142]:
a = torch.ones(4, 3, 2)
b = torch.rand(   3)     # trying to multiply a * b will give a runtime error
try:
    print(a * b)
except Exception as e:
    print(f"Error occured : {e}")
c = b.unsqueeze(1)       # change to a 2-dimensional tensor, adding new dim at the end
print(c.shape)
print(a * c)             # broadcasting works again!

Error occured : The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 2
torch.Size([3, 1])
tensor([[[0.3851, 0.3851],
         [0.0732, 0.0732],
         [0.3118, 0.3118]],

        [[0.3851, 0.3851],
         [0.0732, 0.0732],
         [0.3118, 0.3118]],

        [[0.3851, 0.3851],
         [0.0732, 0.0732],
         [0.3118, 0.3118]],

        [[0.3851, 0.3851],
         [0.0732, 0.0732],
         [0.3118, 0.3118]]])


Есть так же возможность использовать inplace методы squeeze/unsqueeze:

In [143]:
batch_me = torch.rand(3, 226, 226)
print(batch_me.shape)
batch_me.unsqueeze_(0)
print(batch_me.shape)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


Операция `reshape` позволяет изменить размерности тензора произволными образом, сохранив кол-во значений тензора.

In [144]:
output3d = torch.rand(6, 20, 20)
print(output3d.shape)

input1d = output3d.reshape(6 * 20 * 20)
print(input1d.shape)

# can also call it as a method on the torch module:
print(torch.reshape(output3d, (6 * 20 * 20,)).shape)

torch.Size([6, 20, 20])
torch.Size([2400])
torch.Size([2400])


## Связь `torch.tensor` c `numpy`

PyTorch позволяет создавать тензоры непосредственно из имеющихся np.array объектов. Более того, torch.tensor будет указывать на память выделенную первоначально в numpy.array

In [145]:
numpy_array = np.ones((2, 3))
print(numpy_array)

pytorch_tensor = torch.from_numpy(numpy_array)
print(pytorch_tensor)

print(f"Use same memory : {pytorch_tensor.data_ptr() == numpy_array.ctypes.data}")

[[1. 1. 1.]
 [1. 1. 1.]]
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
Use same memory : True


В обратную сторону `torch` -> `numpy` преобразование так же работает

In [146]:
pytorch_rand = torch.rand(2, 3)
print(pytorch_rand)

numpy_rand = pytorch_rand.numpy()
print(numpy_rand)

tensor([[0.1874, 0.3136, 0.7793],
        [0.8340, 0.3402, 0.9330]])
[[0.18740034 0.31359702 0.77929854]
 [0.834021   0.3401633  0.9329737 ]]
